Feat profile user
PatrickSant0s/Link-Buy pull request #12
Opened 2024-10-08 01:00 UTC by PatrickSant0s

Este PR implementa a criação e atualização do perfil do usuário na aplicação, utilizando Vuetify e integração com Supabase para armazenamento de imagens de perfil. As principais funcionalidades incluem:

Exibição do Perfil do Usuário:

O componente exibe o perfil do usuário com nome de usuário, e-mail e avatar.
O avatar pode ser atualizado pelo usuário via upload de imagem, com armazenamento em um bucket do Supabase.
A imagem do perfil é recuperada e exibida corretamente após o upload.

Funcionalidade de Edição:

A opção de editar o perfil está disponível via um modal de diálogo.
O usuário pode alterar o nome de usuário e a senha, com validações de entrada:
O nome de usuário deve conter pelo menos 3 caracteres.
A senha deve ter pelo menos 6 caracteres e incluir um caractere especial.
Upload e Atualização da Imagem de Perfil:

O componente permite o upload de uma nova imagem de perfil.
A imagem é enviada para o bucket do Supabase e o link público da imagem é atualizado no perfil do usuário.
Validações e tratamento de erros foram implementados para garantir a correta atualização da imagem.
Ações do Usuário:

Botão para voltar à tela inicial.
Botão para abrir o modal de edição, onde o usuário pode atualizar as informações do perfil.

2024-10-15 11:48 UTC, JosueFS commented on src/components/MenuBar.vue
> +		if (savedUser && savedUser.avatarUrl) {
Não estou lembrado se isso é suportado pelo vue.js na versão que estamos utilizando nesse projeto, mas existe uma short-syntax para ter apenas uma condicional ao invés de duas utilizando um optional chaining `?.`:

```suggestion
		if (savedUser?.avatarUrl) {
```

2024-10-15 11:48 UTC, JosueFS commented on src/components/MenuBar.vue
> +		} else if (user && user.user_metadata) {
https://github.com/PatrickSant0s/Link-Buy/pull/12/files#r1801014408
Mesma coisa do comentário acima:

```suggestion
		} else if (user?.user_metadata) {
```

2024-10-15 11:52 UTC, JosueFS commented on src/components/CardProfile.vue
> +		} else if (user && user.user_metadata) {
Não estou lembrado se isso é suportado pelo vue.js na versão que estamos utilizando nesse projeto, mas existe uma short-syntax para ter apenas uma condicional ao invés de duas utilizando um optional chaining `?.`:
```suggestion
		if (savedUser?.avatarUrl) {
			this.avatarUrl = savedUser.avatarUrl; // Carrega do localStorage
		} else if (user?.user_metadata) {
```

Leia mais sobre esse tópico, é uma feature do es5/es6 muito utilizada, existe uma grande chance de você encontrar esse tipo de código em algum projeto que você trabalhará: [Optional Chaining](https://medium.com/@guigaoliveira_/entendendo-o-optional-chaining-no-javascript-964ca6928598)

2024-10-15 11:54 UTC, JosueFS requested changes
Fala monstro, deixei alguns comentários para melhorar um pouco mais o código mas sem mudar a idéia geral do que foi feito, assim que resolvido podemos subir.

2024-10-15 12:04 UTC, PatrickSant0s commented
Beleza monstro! Assim que chegar do trabalho vou olhar com mais atenção e
tentar fazer as alterações e melhorias indicadas.


Em ter., 15 de out. de 2024 às 08:54, Josué F. ***@***.***>
escreveu:

> ***@***.**** requested changes on this pull request.
>
> Fala monstro, deixei alguns comentários para melhorar um pouco mais o
> código mas sem mudar a idéia geral do que foi feito, assim que resolvido
> podemos subir.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/PatrickSant0s/Link-Buy/pull/12#pullrequestreview-2369101446>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7TD2F6YER4SFBIN3M66V6TZ3T7ABAVCNFSM6AAAAABPRCC7HWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNRZGEYDCNBUGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-18 11:57 UTC, PatrickSant0s commented on src/components/MenuBar.vue
> +		if (savedUser && savedUser.avatarUrl) {
![image](https://github.com/user-attachments/assets/fc4026bd-4042-4acf-9ff6-b35604106afb)
obrigado pela dica monstro

2024-10-18 11:57 UTC, PatrickSant0s commented on src/components/MenuBar.vue
> +		} else if (user && user.user_metadata) {
![image](https://github.com/user-attachments/assets/40a2d584-f80d-4381-b945-0c4d5018c0cc)
ajustado

2024-10-18 11:57 UTC, PatrickSant0s commented on src/components/CardProfile.vue
> +		} else if (user && user.user_metadata) {
![image](https://github.com/user-attachments/assets/63ab2cd2-4c41-4235-8c73-65fec7929919)

2024-10-29 11:28 UTC, merged